### ISSUE TITLE
How to measure the memory used by the GPU

### ISSUE THREAD

**Issue by Hinataee** [facebookresearch/forwardgnn#1]
Hi, I have a question for the following context in the paper:

> For memory usage, we measured the memory used by the GPU for loading the model parameters, activations, gradients, and the first and second moments of the gradients.

However, I couldn’t find the corresponding code for measuring GPU memory usage. Could you please clarify how to specifically measure the memory used by the GPU? Thanks.

**Comment by namyongp** [comment]
Hi, I basically followed [this article](https://medium.com/deep-learning-for-protein-design/a-comprehensive-guide-to-memory-usage-in-pytorch-b9b7c78031d3) (steps 1-4 and conclusion). For more in-depth analysis, [Pytorch Profiler](https://pytorch.org/tutorials/recipes/recipes/profiler_recipe.html) might be useful.
